### ISSUE TITLE
Problem saving album.

### ISSUE THREAD

**Issue by TemplarGarden** [skarrok/zvuk-dl-rs#1]
Hello. If there is a colon in the release title, then I can't upload such an album due to an error - os error 267.

**Comment by TemplarGarden** [comment]
Yes. I have a windows system.

**Comment by skarrok** [comment]
Try new version https://github.com/skarrok/zvuk-dl-rs/releases/tag/v0.2.1

Reserved characters such as `:` will be converted to `_`.

**Comment by TemplarGarden** [comment]
Да, теперь нормально всё качает. Спасибо тебе мил человек за такой полезный софт)

**Comment by skarrok** [comment]
I'm glad you enjoy it.
Thanks!
