### ISSUE TITLE
Getting releases metadata Error - Failed to get releases metadata

### ISSUE THREAD

**Issue by TemplarGarden** [skarrok/zvuk-dl-rs#2]
**Hello. There was a problem with downloading again. Unable to get metadata from release.**

←[2m2024-11-29T09:53:05.311204Z←[0m ←[34mDEBUG←[0m ←[2mzvuk_dl::config←[0m←[2m:←[0m Config download_lyrics=true
←[2m2024-11-29T09:53:05.311317Z←[0m ←[34mDEBUG←[0m ←[2mzvuk_dl::config←[0m←[2m:←[0m Config embed_cover=false
←[2m2024-11-29T09:53:05.311360Z←[0m ←[34mDEBUG←[0m ←[2mzvuk_dl::config←[0m←[2m:←[0m Config log_format="Console"
←[2m2024-11-29T09:53:05.311417Z←[0m ←[34mDEBUG←[0m ←[2mzvuk_dl::config←[0m←[2m:←[0m Config log_level="Debug"
←[2m2024-11-29T09:53:05.311464Z←[0m ←[34mDEBUG←[0m ←[2mzvuk_dl::config←[0m←[2m:←[0m Config pause_between_getting_track_links={"nanos":0,"secs":1}
←[2m2024-11-29T09:53:05.311510Z←[0m ←[34mDEBUG←[0m ←[2mzvuk_dl::config←[0m←[2m:←[0m Config quality="Flac"
←[2m2024-11-29T09:53:05.311549Z←[0m ←[34mDEBUG←[0m ←[2mzvuk_dl::config←[0m←[2m:←[0m Config resize_command="magick {source} -define jpeg:extent=1MB {target}"
←[2m2024-11-29T09:53:05.311593Z←[0m ←[34mDEBUG←[0m ←[2mzvuk_dl::config←[0m←[2m:←[0m Config resize_cover=true
←[2m2024-11-29T09:53:05.311632Z←[0m ←[34mDEBUG←[0m ←[2mzvuk_dl::config←[0m←[2m:←[0m Config resize_cover_limit=2000000
←[2m2024-11-29T09:53:05.311671Z←[0m ←[34mDEBUG←[0m ←[2mzvuk_dl::config←[0m←[2m:←[0m Config token="******"
←[2m2024-11-29T09:53:05.311709Z←[0m ←[34mDEBUG←[0m ←[2mzvuk_dl::config←[0m←[2m:←[0m Config urls=["https://zvuk.com/release/672066"]
←[2m2024-11-29T09:53:05.312210Z←[0m ←[32m INFO←[0m ←[2mzvuk_dl::zvuk←[0m←[2m:←[0m Getting releases metadata
Error: Failed to get releases metadata

Caused by:
    0: Failed to parse releses metadata
    1: error decoding response body
    2: expected value at line 1 column 1

**Comment by skarrok** [comment]
Hi! Thanks for the report.

I think I fixed it. Please try the new version from https://github.com/skarrok/zvuk-dl-rs/releases/tag/v0.2.2 and let me know the result.

**Comment by TemplarGarden** [comment]
I checked. Now it works. Thank you!
